# Generated by Django 4.2 on 2024-01-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="image",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
