# Generated by Django 4.2 on 2024-01-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0002_alter_images_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Название"),
        ),
    ]
